name = "NeuroPlots"
uuid = "1f2ffea9-73bd-5d04-b319-71eab08f4cf7"
version = "0.1.8"
authors = ["Galen Lynch <galen@galenlynch.com>"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DynamicTimeseries = "1899e1d9-0e62-5b08-93e8-96938e3582a6"
EventIntervals = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
SignalIndices = "18f53e89-494d-4131-905c-653e8ada6cd8"
SortedIntervals = "b6c59e15-8662-4f8a-b157-cd910e143dcd"
PyQtGraph = "3671797b-b403-50f8-ae8f-9a67aa3877b6"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgCheck = "1"
DynamicTimeseries = "0.0.5 - 0.1"
EventIntervals = "0.0.2 - 0.1"
SignalIndices = "0.1"
SortedIntervals = "0.1"
PyQtGraph = "0.0.2 - 0.1"
PythonCall = "0.9.31"
PythonPlot = "1.0.6"
julia = "1.6"
