name = "GLPlotting"
uuid = "1f2ffea9-73bd-5d04-b319-71eab08f4cf7"
authors = ["Galen Lynch <galen.lynch@gmail.com>"]
version = "0.1.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GLTimeseries = "1899e1d9-0e62-5b08-93e8-96938e3582a6"
GLUtilities = "8b4c6747-1f02-570a-a961-a96037df41d6"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
PointProcesses = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
PyQtGraph = "3671797b-b403-50f8-ae8f-9a67aa3877b6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArgCheck = "1"
Compat = "1 - 3"
GLTimeseries = "0.0.5 - 0.1"
GLUtilities = "0.0.5 - 0.2"
Missings = "0.2 - 0.4"
PointProcesses = "0.0.2 - 0.1"
PyCall = "1.11"
PyPlot = "2"
PyQtGraph = "0.0.2 - 0.1"
julia = "0.6 - 1"
